[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 301
  force = false
  query = {path = ":path"}
